version: '3.4'

services:
  mysql:
    image: mysql:8.0.21
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=general-user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nest-sample
    ports:
      - target: 3306
        published: 3306
        mode: host
